export const CATEGORIES = [
  {
    id: '1',
    slug: 'politics' as const,
    name: 'Politics',
    description: 'Political news and analysis',
    icon: 'landmark',
    color: 'blue',
  },
  {
    id: '2',
    slug: 'technology' as const,
    name: 'Technology',
    description: 'Tech news and innovations',
    icon: 'zap',
    color: 'purple',
  },
  {
    id: '3',
    slug: 'sports' as const,
    name: 'Sports',
    description: 'Sports events and updates',
    icon: 'trophy',
    color: 'emerald',
  },
  {
    id: '4',
    slug: 'business' as const,
    name: 'Business',
    description: 'Business and finance news',
    icon: 'briefcase',
    color: 'amber',
  },
  {
    id: '5',
    slug: 'science' as const,
    name: 'Science',
    description: 'Science discoveries',
    icon: 'microscope',
    color: 'violet',
  },
  {
    id: '6',
    slug: 'entertainment' as const,
    name: 'Entertainment',
    description: 'Entertainment news',
    icon: 'popcorn',
    color: 'pink',
  },
  {
    id: '7',
    slug: 'health' as const,
    name: 'Health',
    description: 'Health and wellness',
    icon: 'heart',
    color: 'red',
  },
  {
    id: '8',
    slug: 'world-news' as const,
    name: 'World News',
    description: 'Global news',
    icon: 'globe',
    color: 'cyan',
  },
  {
    id: '9',
    slug: 'environment' as const,
    name: 'Environment',
    description: 'Climate and environmental news',
    icon: 'leaf',
    color: 'green',
  },
  {
    id: '10',
    slug: 'education' as const,
    name: 'Education',
    description: 'Education and learning',
    icon: 'graduation-cap',
    color: 'indigo',
  },
  {
    id: '11',
    slug: 'lifestyle' as const,
    name: 'Lifestyle',
    description: 'Lifestyle and culture',
    icon: 'coffee',
    color: 'orange',
  },
  {
    id: '12',
    slug: 'travel' as const,
    name: 'Travel',
    description: 'Travel and tourism',
    icon: 'plane',
    color: 'sky',
  },
  {
    id: '13',
    slug: 'food' as const,
    name: 'Food',
    description: 'Food and cuisine',
    icon: 'utensils',
    color: 'rose',
  },
  {
    id: '14',
    slug: 'automotive' as const,
    name: 'Automotive',
    description: 'Cars and vehicles',
    icon: 'car',
    color: 'slate',
  },
  {
    id: '15',
    slug: 'real-estate' as const,
    name: 'Real Estate',
    description: 'Property and housing',
    icon: 'home',
    color: 'teal',
  },
  {
    id: '16',
    slug: 'finance' as const,
    name: 'Finance',
    description: 'Personal finance and investing',
    icon: 'dollar-sign',
    color: 'yellow',
  },
  {
    id: '17',
    slug: 'fashion' as const,
    name: 'Fashion',
    description: 'Fashion and style',
    icon: 'shirt',
    color: 'fuchsia',
  },
  {
    id: '18',
    slug: 'arts' as const,
    name: 'Arts',
    description: 'Arts and culture',
    icon: 'palette',
    color: 'purple',
  },
  {
    id: '19',
    slug: 'gaming' as const,
    name: 'Gaming',
    description: 'Video games and esports',
    icon: 'gamepad',
    color: 'violet',
  },
  {
    id: '20',
    slug: 'opinion' as const,
    name: 'Opinion',
    description: 'Opinions and editorials',
    icon: 'message-square',
    color: 'gray',
  },
];

export const SITE_NAME = 'Chronicle AI';
export const SITE_DESCRIPTION =
  'Your AI-Powered News Intelligence Platform';
